services:
  db:
    image: postgres
    restart: always
    container_name: budgeting_db
    user: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5332:5432"
  adminer:
    image: adminer
    restart: always
    container_name: budgeting_adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:
